cyka: test object link

test:
	/../info/DD2387/labs/cxxtest/cxxtestgen.py --error-printer \-o simple_testrunner.cpp simple.cxxtest.cpp
object:
	g++ -c -o count_if_followed_by.o count_if_followed_by.cpp
link:
	g++ -o simple_test.out -I /../info/DD2387/labs/cxxtest/ \simple_testrunner.cpp count_if_followed_by.o
